name: PrivateBlocksPlugin
version: '${version}'

main: Bzbxddbx.privateBlocksPlugin.PrivateBlocksPlugin
api-version: '26.2'
load: POSTWORLD

commands:
  pbhelp:
    description: "Показывает информацию о радиусах приват-блоков"
